--- squeezelite-master/Makefile	2017-10-05 23:47:06.351886520 +0200
+++ squeezelite-master/Makefile.new	2017-10-05 23:48:03.164696351 +0200
@@ -1,90 +1,25 @@
-# Cross compile support - create a Makefile which defines these three variables and then includes this Makefile...
-CFLAGS  ?= -Wall -fPIC -O2 $(OPTS)
-LDFLAGS ?= -lasound -lpthread -lm -lrt
+# Makefile CHIP
 EXECUTABLE ?= squeezelite
 
-# passing one or more of these in $(OPTS) enables optional feature inclusion
-OPT_DSD     = -DDSD
-OPT_FF      = -DFFMPEG
-OPT_LINKALL = -DLINKALL
-OPT_RESAMPLE= -DRESAMPLE
-OPT_VIS     = -DVISEXPORT
-OPT_IR      = -DIR
-OPT_GPIO    = -DGPIO
-
-SOURCES = \
-	main.c slimproto.c buffer.c stream.c utils.c \
-	output.c output_alsa.c output_pa.c output_stdout.c output_pack.c decode.c \
-	flac.c pcm.c mad.c vorbis.c faad.c mpg.c
-
-SOURCES_DSD      = dsd.c dop.c dsd2pcm/dsd2pcm.c
-SOURCES_FF       = ffmpeg.c
-SOURCES_RESAMPLE = process.c resample.c
-SOURCES_VIS      = output_vis.c
-SOURCES_IR       = ir.c
-SOURCES_GPIO     = gpio.c
-
-LINK_LINUX       = -ldl
-
-LINKALL          = -lFLAC -lmad -lvorbisfile -lfaad -lmpg123
-LINKALL_FF       = -lavcodec -lavformat -lavutil
-LINKALL_RESAMPLE = -lsoxr
-LINKALL_IR       = -llirc_client
-
-DEPS             = squeezelite.h slimproto.h
-
-UNAME            = $(shell uname -s)
-
-# add optional sources
-ifneq (,$(findstring $(OPT_DSD), $(CFLAGS)))
-	SOURCES += $(SOURCES_DSD)
-endif
-ifneq (,$(findstring $(OPT_FF), $(CFLAGS)))
-	SOURCES += $(SOURCES_FF)
-endif
-ifneq (,$(findstring $(OPT_RESAMPLE), $(CFLAGS)))
-	SOURCES += $(SOURCES_RESAMPLE)
-endif
-ifneq (,$(findstring $(OPT_VIS), $(CFLAGS)))
-	SOURCES += $(SOURCES_VIS)
-endif
-ifneq (,$(findstring $(OPT_IR), $(CFLAGS)))
-	SOURCES += $(SOURCES_IR)
-endif
-ifneq (,$(findstring $(OPT_GPIO), $(CFLAGS)))
-	SOURCES += $(SOURCES_GPIO)
-endif
-
-# add optional link options
-ifneq (,$(findstring $(OPT_LINKALL), $(CFLAGS)))
-	LDFLAGS += $(LINKALL)
-ifneq (,$(findstring $(OPT_FF), $(CFLAGS)))
-	LDFLAGS += $(LINKALL_FF)
-endif
-ifneq (,$(findstring $(OPT_RESAMPLE), $(CFLAGS)))
-	LDFLAGS += $(LINKALL_RESAMPLE)
-endif
-ifneq (,$(findstring $(OPT_IR), $(CFLAGS)))
-	LDFLAGS += $(LINKALL_IR)
-endif
-else
-# if not LINKALL and linux add LINK_LINUX
-ifeq ($(UNAME), Linux)
-	LDFLAGS += $(LINK_LINUX)
-endif
-endif
+SOURCES = main.c slimproto.c utils.c buffer.c stream.c decode.c flac.c pcm.c mad.c vorbis.c output_alsa.c output.c output_pa.c output_pack.c output_stdout.c output_vis.c dop.c dsd.c dsd2pcm/dsd2pcm.c faad.c mpg.c resample.c process.c ffmpeg.c
+DEPS    = squeezelite.h slimproto.h dsd2pcm/dsd2pcm.h
 
 OBJECTS = $(SOURCES:.c=.o)
 
+.PHONY: all strip clean
+
 all: $(EXECUTABLE)
 
+strip: $(EXECUTABLE)
+	$(STRIP) -s $< -o $<-stripped
+
 $(EXECUTABLE): $(OBJECTS)
 	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
 
 $(OBJECTS): $(DEPS)
 
 .c.o:
-	$(CC) $(CFLAGS) $(CPPFLAGS) $< -c -o $@
+	$(CC) $(CFLAGS) $< -c -o $@
 
 clean:
-	rm -f $(OBJECTS) $(EXECUTABLE)
+	rm -f $(OBJECTS) $(EXECUTABLE)*
