#!/bin/sh

case "$1" in
	start)
		if [ ! -d /data/mender ]; then
			/bin/mkdir -p -m 0700 /data/mender
		fi
		if [ ! -f /data/mender/device_type ]; then
			echo "device_type=chip" > /data/mender/device_type
		fi
		;;
	*)
		echo "usage: $0 {start}"
		;;
esac

